# Generated by Django 3.0.5 on 2024-09-20 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_id',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
