# Generated by Django 3.0.5 on 2024-09-20 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='order',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='product_id',
        ),
    ]
