# Generated by Django 3.0.5 on 2024-09-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_auto_20240921_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='street',
            field=models.CharField(max_length=100),
        ),
    ]
