# Generated by Django 3.0.5 on 2024-09-24 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_order_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='image',
            new_name='pimage',
        ),
    ]
