# Generated by Django 3.0.5 on 2024-09-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_auto_20240924_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pimage',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pimage',
            field=models.ImageField(blank=True, null=True, upload_to='order_images/'),
        ),
    ]
