# Generated by Django 3.0.5 on 2024-09-25 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0022_auto_20240924_2126'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
