# Generated by Django 3.0.5 on 2024-09-25 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0025_auto_20240925_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
