# Generated by Django 3.0.5 on 2024-09-25 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0028_order_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
    ]
