# Generated by Django 5.1.1 on 2024-09-29 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0035_remove_address_user_address_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='street',
            new_name='full_address',
        ),
    ]
