# Generated by Django 3.0.5 on 2024-08-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurent_manager', '0004_auto_20240831_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='food_description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='food_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='food_price',
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('out_of_stock', 'Out of Stock'), ('seasonal', 'Seasonal')], default='available', max_length=20),
        ),
    ]
