# Generated by Django 3.0.5 on 2024-09-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurent_manager', '0007_auto_20240918_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='Deliverable',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='available', max_length=20),
        ),
    ]
