# Generated by Django 3.0.5 on 2024-09-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurent_manager', '0008_auto_20240918_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Deliverable',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
