# Generated by Django 3.0.5 on 2024-09-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurent_manager', '0009_auto_20240918_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Deliverable',
            field=models.CharField(max_length=20),
        ),
    ]
