# Generated by Django 3.0.5 on 2024-09-18 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurent_manager', '0010_auto_20240918_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
    ]
