# Generated by Django 3.0.5 on 2024-09-18 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurent_manager', '0012_auto_20240918_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
